import type { S3Event } from 'aws-lambda';
import { parseS3Event, S3EventParseError } from './s3-event-parser';
import { getImageFromS3, ImageValidationError } from './image-retrieval';
import { detectLabels, selectTopLabels } from './rekognition-service';
import { constructPrompt } from './prompt-constructor';
import { generateContent } from './bedrock-service';
import { generateFallbackContent } from './fallback-content';
import { updateItemRecord } from './dynamodb-update';
import { logInfo, logError } from './logger';

/**
 * Lambda handler for AI Image Analysis
 * Triggered by S3 uploads to process images with Rekognition and Bedrock
 * 
 * Requirements:
 * - 1.1: Trigger within 2 seconds of S3 upload
 * - 1.2: Extract S3 object key and bucket name
 * - 1.3: Validate image format
 * - 1.4: Retrieve image from S3
 * - 7.2: Log processing start with image key and timestamp
 * - 7.3: Log processing completion with metadata and duration
 * - 7.4: Implement top-level error handling with logging
 */
export const handler = async (event: S3Event): Promise<void> => {
  const startTime = Date.now();
  let imageKey = 'unknown';
  let itemId = 'unknown';

  try {
    // Parse S3 event and extract bucket/key
    // Requirements: 1.2
    const { bucket, key } = parseS3Event(event);
    imageKey = key;
    
    // Extract itemId from S3 key (e.g., "uploads/item-123.jpg" -> "item-123")
    itemId = extractItemId(key);
    
    // Log processing start with image key and timestamp
    // Requirements: 7.2
    logInfo('Image analysis started', {
      imageKey,
      itemId,
      bucket,
      timestamp: new Date().toISOString()
    });

    // Call image retrieval module
    // Requirements: 1.3, 1.4
    const imageBuffer = await getImageFromS3(bucket, key);
    
    logInfo('Image retrieved successfully', {
      imageKey,
      itemId,
      size: imageBuffer.length
    });

    // Call Rekognition service module
    // Requirements: 2.1, 2.2, 2.3, 2.4, 2.5
    const detectedLabels = await detectLabels(imageBuffer);
    const topLabels = selectTopLabels(detectedLabels);
    
    logInfo('Labels detected', {
      imageKey,
      itemId,
      labelCount: topLabels.length,
      labels: topLabels.map(l => l.name)
    });

    // Call Bedrock service module (with fallback on failure)
    // Requirements: 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7
    let generatedContent;
    
    try {
      const prompt = constructPrompt(topLabels);
      generatedContent = await generateContent(prompt);
      
      logInfo('Content generated by Bedrock', {
        imageKey,
        itemId,
        title: generatedContent.title,
        condition: generatedContent.condition
      });
    } catch (bedrockError) {
      // Use fallback content generation if Bedrock fails
      logError({
        operation: 'generateContent',
        service: 'Bedrock',
        error: bedrockError instanceof Error ? bedrockError : new Error(String(bedrockError)),
        metadata: { imageKey, itemId }
      });
      
      logInfo('Using fallback content generation', {
        imageKey,
        itemId
      });
      
      generatedContent = generateFallbackContent(topLabels);
    }

    // Call DynamoDB update module
    // Requirements: 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7
    await updateItemRecord({
      itemId,
      aiTags: topLabels.map(l => l.name),
      aiDescription: generatedContent.description,
      aiConditionAssessment: generatedContent.condition
    });

    // Log processing completion with metadata and duration
    // Requirements: 7.3
    const duration = Date.now() - startTime;
    logInfo('Image analysis completed successfully', {
      imageKey,
      itemId,
      duration,
      metadata: {
        title: generatedContent.title,
        description: generatedContent.description,
        condition: generatedContent.condition,
        tags: topLabels.map(l => l.name),
        labelCount: topLabels.length
      }
    });

  } catch (error) {
    // Implement top-level error handling with logging
    // Requirements: 7.4
    const duration = Date.now() - startTime;
    
    // Determine error type for better logging
    let errorType = 'UnknownError';
    if (error instanceof S3EventParseError) {
      errorType = 'S3EventParseError';
    } else if (error instanceof ImageValidationError) {
      errorType = 'ImageValidationError';
    }
    
    logError({
      operation: 'handler',
      service: 'ImageAnalyzer',
      error: error instanceof Error ? error : new Error(String(error)),
      metadata: {
        imageKey,
        itemId,
        duration,
        errorType
      }
    });

    // Re-throw error to signal Lambda failure
    throw error;
  }
};

/**
 * Extracts itemId from S3 object key
 * Example: "uploads/item-123.jpg" -> "item-123"
 * 
 * @param key - S3 object key
 * @returns Extracted itemId
 */
function extractItemId(key: string): string {
  // Remove path prefix and file extension
  const filename = key.split('/').pop() || key;
  const itemId = filename.replace(/\.[^/.]+$/, ''); // Remove extension
  return itemId;
}
